### ISSUE TITLE
Problem with import ProDy from NMWiz

### ISSUE THREAD

**Issue by jamesmkrieger** [prody/NMWiz#4]
Here is an error reported to me by Yasir Khan via Facebook.

```
I have a work station, i work on molecular dynamics simulations using desmond. Now i have to perform PCA i searched internet got suggestions to use Prody in VMD, i worked on it set it up but now some error occurs. I once noticed you being expert in this area and i guess you share the authorship of prody as well so i thought may be you can help?
```

```
raceback (most recent call last):
  File "/usr/local/bin/prody", line 5, in <module>
    from prody.apps import prody_main
  File "/usr/local/lib/python3.8/dist-packages/prody/__init__.py", line 88, in <module>
    from . import proteins
  File "/usr/local/lib/python3.8/dist-packages/prody/proteins/__init__.py", line 155, in <module>
    from . import compare
  File "/usr/local/lib/python3.8/dist-packages/prody/proteins/compare.py", line 16, in <module>
    from prody.sequence import MSA
  File "/usr/local/lib/python3.8/dist-packages/prody/sequence/__init__.py", line 53, in <module>
    from . import msa
  File "/usr/local/lib/python3.8/dist-packages/prody/sequence/msa.py", line 9, in <module>
    from Bio import AlignIO
  File "/usr/local/lib/python3.8/dist-packages/Bio/AlignIO/__init__.py", line 147, in <module>
    from . import MafIO
  File "/usr/local/lib/python3.8/dist-packages/Bio/AlignIO/MafIO.py", line 38, in <module>
    from sqlite3 import dbapi2
  File "/usr/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
Traceback (most recent call last):
  File "/usr/local/bin/prody", line 5, in <module>
    from prody.apps import prody_main
  File "/usr/local/lib/python3.8/dist-packages/prody/__init__.py", line 88, in <module>
    from . import proteins
  File "/usr/local/lib/python3.8/dist-packages/prody/proteins/__init__.py", line 155, in <module>
    from . import compare
  File "/usr/local/lib/python3.8/dist-packages/prody/proteins/compare.py", line 16, in <module>
    from prody.sequence import MSA
  File "/usr/local/lib/python3.8/dist-packages/prody/sequence/__init__.py", line 53, in <module>
    from . import msa
  File "/usr/local/lib/python3.8/dist-packages/prody/sequence/msa.py", line 9, in <module>
    from Bio import AlignIO
  File "/usr/local/lib/python3.8/dist-packages/Bio/AlignIO/__init__.py", line 147, in <module>
    from . import MafIO
  File "/usr/local/lib/python3.8/dist-packages/Bio/AlignIO/MafIO.py", line 38, in <module>
    from sqlite3 import dbapi2
  File "/usr/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /usr/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so: undefined symbol: sqlite3_errstr
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody anm --quiet -s $selstr {*}$args "$pdbfn""
    (procedure "::NMWiz::prodySubmitANMjob" line 42)
    invoked from within
"::NMWiz::prodySubmitANMjob"
    (procedure "::NMWiz::prodySubmitJob" line 22)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 22)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)
```

**Comment by jamesmkrieger** [comment]
Same happens with 2k39 with ANM

**Comment by jamesmkrieger** [comment]
A workaround for now is to use the prody app from the command line and load in the nmd file into VMD

**Comment by jamesmkrieger** [comment]
Updating pysqlite3 didn't help

**Comment by jamesmkrieger** [comment]
The solution should be to use conda as in https://github.com/prody/ProDy/issues/1432

**Comment by jamesmkrieger** [comment]
Yes, that fixed it
